### ISSUE TITLE
Version 0.1

### ISSUE THREAD

**Issue by jordanisaacs** [jordanisaacs/neovim-flake#16]
Steps to tagging a 0.1 release.

- [x] Fix evaluation steps and builder function.
- [x] Use DAG for ordering config.
- [x] Fix treesitter installation.
- [x] Make buildable on other platforms
- [x] Auto generate docs using nmd  
- [x] Rewrite the README
- [x] Write a changelog from untagged master
- [x] Write docs for custom configuration
- [x] Use [nvim-treesitter](https://discourse.nixos.org/t/psa-if-you-are-on-unstable-try-out-nvim-treesitter-withallgrammars) grammars
- [ ] Write a flake template
- [ ] Module option to install docs
- [x] Extendable configuration #28 #23 
- [x] Move build into the module #30 
- [x] A good solution to extra inputs #18 #30 
- [x] Refactor languages/lsp/treesitter into their own section (#29 )
- [x] Update nmd
- [x] Add CONTRIBUTING.md
